// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukapxotdkjkqgarwehva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrYXB4b3Rka2prcWdhcndlaHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDE5MDUsImV4cCI6MjA2MDUxNzkwNX0.Dy_vsDHmN1s61DVRD11HgusBB7Re1FXIazJTAjeWZAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);